function [labels, values] = snap_beamform(flat_i, flat_v,...
                                          ichan, threshold,...
                                          beam_delays, max_beams,...
                                          max_labels,...
                                          ndim1, ndim2)
numchan = numel(ichan);
% there is no shape checking in fortran routine, so do it in matlab
if numel(flat_i) <= 1
    error('need to have more than one value for beamforming')
end

if size(flat_i, 1) == 1
    flat_i = flat_i.';
end

if size(flat_v, 1) == 1
    flat_v = flat_v.';
end

if size(beam_delays, 1) ~= numchan
    beam_delays = beam_delays.';
end

[lbout, vbout, nlbal] = smaty(int32(flat_i),...
                              flat_v,....
                              int32(ichan),...
                              threshold,....
                              int32(beam_delays),...
                              int32(max_beams),...
                              int32(max_labels),...
                              int32(ndim1),...
                              int32(ndim2));
                          
vbout = vbout(1: nlbal);
lbout = lbout(:, 1: nlbal);

values = double(vbout);
labels = double(lbout);
